cabinet_config: cabinets.yaml
filenames:
  australia-3642062668-86: READMEf
  export-3642062668-86: c
  japan-3642062668-86: READMEa
  korea-3642062668-86: d
  usa-3642062668-86: b
patch_directory:
- /home/dragonminded/netboot/patches
rom_directory:
- /home/dragonminded/netboot/roms
